version: '3.8'

services:
  api:
    build:
      context: ./src/backend/TimSynergy.API
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CosmosDb__Endpoint=${COSMOS_DB_ENDPOINT}
      - CosmosDb__Key=${COSMOS_DB_KEY}
      - CosmosDb__DatabaseName=${COSMOS_DB_NAME}
    depends_on:
      - cosmos-db-emulator

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

  cosmos-db-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    mem_limit: 3g
    cpu_count: 2
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    ports:
      - "8081:8081"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
    volumes:
      - cosmos-db-emulator:/data/db
      
volumes:
  cosmos-db-emulator:
